### ISSUE TITLE
Deb package creation broken due to updated Ruby containers (and bug in FPM?)

### ISSUE THREAD

**Issue by bedroge** [bpicode/github-action-fpm#3]
Somehow the deb package generation in FPM does not seem to work with Ruby 3 anymore, see for instance:
https://github.com/EESSI/filesystem-layer/issues/64
Last month, someone already made a PR with a fix in the FPM repository, but this still hasn't been merged yet...

Since this github action automatically takes the latest Ruby container from Docker Hub, this functionality is also broken here now. I just did some manual tests and these confirmed that it still works fine with, for instance, `ruby:2-alpine`. Would it be possible to stick to that version for now (possibly on a separate branch), until the PR in the FPM project gets merged?

**Comment by bpicode** [comment]
Hi, thanks for letting me know :+1:
Yes, we should go with the ruby:2-alpine image for now. Even if https://github.com/jordansissel/fpm/pull/1740 gets merged, I would still want to wait until there is a tagged release.

**Comment by bedroge** [comment]
Great, thanks for the really quick fix! :-)
